[package]
name = "v5_stack"
version = "0.1.0"
authors = ["Todd Pickell <tapickell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
